### ISSUE TITLE
Link IPTV de PlutoTV no encontrado

### ISSUE THREAD

**Issue by jasimancas** [davidmuma/Docker_dobleM#1]
Buenas, ante todo gran curro el que te pegas con esto.

He lanzado el script y por lo que veo me ha generado tanto PlutoTV como TDT pero da un 404 y veo que los enlaces que te paso a continuación no existen en tu repositorio de git:

https://raw.githubusercontent.com/davidmuma/log_dobleM/master/PlutoTV_ES.m3u
https://raw.githubusercontent.com/davidmuma/log_dobleM/master/TDTChannels.m3u

**Comment by davidmuma** [comment]
Solucionado, gracias por avisar
